name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: app

      - name: Lint
        run: npm run lint
        working-directory: app

      - name: Run unit tests with coverage
        run: npm run test -- --coverage
        working-directory: app

      - name: Build project
        run: npm run build
        working-directory: app
